[package]
name = "gadget-runner-core"
version = "0.1.0"
description = "Runner core primitives for Tangle Blueprints"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# Core
gadget-config = { workspace = true }
gadget-utils = { workspace = true }
gadget-event-listeners = { workspace = true, default-features = false }
async-trait = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["sync"] }

# Error
thiserror = { workspace = true }

# Logging
gadget-logging = { workspace = true }

[features]
default = ["std"]

std = ["gadget-config/std", "gadget-utils/std", "gadget-logging/std", "gadget-event-listeners/std"]
web = ["gadget-utils/web"]

eigenlayer = ["gadget-config/eigenlayer", "gadget-utils/eigenlayer", "gadget-event-listeners/evm"]
symbiotic = ["gadget-config/symbiotic", "gadget-event-listeners/evm"]
tangle = ["gadget-config/tangle", "gadget-utils/tangle", "gadget-event-listeners/tangle"]
