[package]
name = "gadget-chain-setup-tangle"
version = "0.1.0"
description = "Tangle-specific chain setup utilities"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gadget-std = { workspace = true }
tracing = { workspace = true }
dirs = { workspace = true }
reqwest = { workspace = true, features = ["json", "default-tls"] }
serde_json = { workspace = true }
color-eyre = { workspace = true }
indicatif = { workspace = true }
dialoguer = { workspace = true }

gadget-networking = { workspace = true }
gadget-contexts = { workspace = true, features = ["tangle"] }
gadget-crypto-tangle-pair-signer = { workspace = true, features = ["evm"] }
blueprint-tangle-extra = { workspace = true, features = ["metadata-types"] }
blueprint-core = { workspace = true }
gadget-clients = { workspace = true, features = ["tangle"] }
gadget-keystore = { workspace = true }
gadget-blueprint-serde = { workspace = true }
gadget-chain-setup-common = { workspace = true }
gadget-crypto = { workspace = true, features = [
    "k256",
    "sr25519-schnorrkel",
    "ed25519",
    "bls",
    "bn254",
    "sp-core",
    "sp-core-bls",
    "tangle-pair-signer",
] }

alloy-provider = { workspace = true, features = ["ws"] }
alloy-signer-local = { workspace = true }
alloy-rpc-types = { workspace = true, features = ["eth"] }
alloy-rpc-types-eth = { workspace = true }
alloy-json-abi = { workspace = true }
alloy-transport = { workspace = true }
alloy-network = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
sp-core = { workspace = true }
tangle-subxt = { workspace = true }

thiserror = { workspace = true }
cargo_metadata = { workspace = true }

[features]
default = ["std"]
std = [
    "blueprint-tangle-extra/std",
    "sp-core/std",
    "tangle-subxt/std",
    "gadget-std/std",
    "gadget-networking/std",
    "gadget-contexts/std",
    "gadget-crypto-tangle-pair-signer/std",
    "gadget-clients/std",
    "gadget-keystore/std",
    "gadget-blueprint-serde/std",
    "thiserror/std",
]
