[package]
name = "gadget-runner-eigenlayer"
version = "0.1.0"
description = "EigenLayer-specific runner for Tangle Blueprints"
edition = "2021"

[dependencies]
gadget-runner-core = { workspace = true, default-features = false, features = ["eigenlayer"] }
alloy-primitives = { workspace = true, default-features = false }
alloy-signer-local = { workspace = true, default-features = false }
alloy-signer = { workspace = true, default-features = false }
alloy-rpc-types = { workspace = true, default-features = false }
alloy-network = { workspace = true, default-features = false }
alloy-provider = { workspace = true, default-features = false }
alloy-contract = { workspace = true, default-features = false }
async-trait = { workspace = true, default-features = false }
gadget-config = { workspace = true, default-features = false, features = ["eigenlayer", "keystore"] }
gadget-logging = { workspace = true, default-features = false }
gadget-utils = { workspace = true, default-features = false, features = ["evm"] }
eigensdk = { workspace = true, default-features = false, features = ["client-elcontracts", "types", "utils", "logging", "client-avsregistry"] }
thiserror = { workspace = true, default-features = false }
gadget-keystore = { workspace = true, default-features = false, features = ["eigenlayer", "tangle"] }
gadget-std = { workspace = true, default-features = false }
gadget-contexts = { workspace = true, default-features = false, features = ["eigenlayer", "keystore", "evm"] }
gadget-eigenlayer-bindings = { workspace = true, default-features = false }

[features]
default = ["std"]

std = [
    "gadget-runner-core/std",
    "gadget-config/std",
    "gadget-logging/std",
    "gadget-utils/std",
    "gadget-keystore/std",
    "gadget-std/std",
]

[dev-dependencies]
rand = { workspace = true, default-features = false, features = ["std_rng"] }