[package]
name = "gadget-core-testing-utils"
version = "0.1.0"
description = "Core primitives for testing Tangle Blueprints"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
blueprint-core = { workspace = true }
blueprint-runner = { workspace = true }
blueprint-router = { workspace = true }

gadget-clients = { workspace = true, features = ["std"] }
gadget-keystore = { workspace = true, features = ["std"] }
cargo_toml = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
