use gadget_blueprint_proc_macro::job;

/// Simple Threashold (t) Keygen Job for n parties.
#[job(id = 0, params(n, t), result(_), verifier(evm = "TestContract"))]
pub fn keygen(n: u16, t: u8) -> Vec<u8> {
    let _ = (n, t);
    vec![0; 33]
}

/// Sign a message using a key generated by the keygen job.
#[job(id = 1, params(keygen_id, data), result(_))]
pub fn sign(keygen_id: u64, data: Vec<u8>) -> Vec<u8> {
    let _ = (keygen_id, data);
    vec![0; 65]
}

#[cfg(test)]
mod tests {

    #[test]
    fn generated_blueprint() {
        eprintln!("{}", super::KEYGEN_JOB_DEF);
        assert_eq!(super::KEYGEN_JOB_ID, 0);
    }
}
