[package]
name = "gadget-chain-setup-common"
version = "0.1.0"
description = "Common chain setup utilities for use with the Blueprint SDK"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gadget-std = { workspace = true }
color-eyre = { workspace = true }

gadget-networking = { workspace = true }
gadget-contexts = { workspace = true, features = ["tangle"] }
gadget-crypto-tangle-pair-signer = { workspace = true, features = ["evm"] }
gadget-clients = { workspace = true, features = ["tangle"] }
gadget-keystore = { workspace = true }
gadget-blueprint-serde = { workspace = true }
gadget-crypto = { workspace = true, features = [
    "k256",
    "sr25519-schnorrkel",
    "ed25519",
    "bls",
    "bn254",
    "sp-core",
    "sp-core-bls",
    "tangle-pair-signer",
] }
alloy-signer-local = { workspace = true }
sp-core = { workspace = true }
tangle-subxt = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["std"]
std = [
    "sp-core/std",
    "tangle-subxt/std",
    "gadget-std/std",
    "gadget-networking/std",
    "gadget-contexts/std",
    "gadget-crypto-tangle-pair-signer/std",
    "gadget-crypto/std",
    "gadget-clients/std",
    "gadget-keystore/std",
    "gadget-blueprint-serde/std",
    "thiserror/std",
]
