mod complex_types;
mod function_with_explicit_empty_return_type;
mod function_without_return_type;
mod infer_result;
mod mixed_types;
mod multiple_params;
mod multiple_results;
mod non_result_return_type;
mod simple;
