[package]
name = "gadget-crypto-ed25519"
version = "0.1.0"
description = "Zebra ed25519 crypto primitives for Tangle Blueprints"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gadget-crypto-core = { workspace = true, features = ["zebra"] }
gadget-std = { workspace = true }
ed25519-zebra = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true, features = ["alloc"] }
hex = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
	"gadget-crypto-core/std",
	"gadget-std/std",
	"serde/std",
	"serde_json/std",
	"serde_bytes/std",
	"ed25519-zebra/std",
] 
